server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
